### ISSUE TITLE
Fragment transitions?

### ISSUE THREAD

**Issue by qaiserhabib** [andkulikov/Transitions-Everywhere#11]
Hello, 

First of all, this is an excellent library and works quite well for scene transitions.

I'm trying to apply it to fragments as enter transitions and I'm not able to use Explode() or ChangeBounds (or any transition) because of the following exception:

Any ideas please? If it doesn't support fragment transitions, do you plan on supporting it someday?

java.lang.ClassCastException: android.transitions.everywhere.ChangeBounds cannot be cast to android.transition.Transition
            at android.support.v4.app.FragmentTransitionCompat21.cloneTransition(FragmentTransitionCompat21.java:41)
            at android.support.v4.app.BackStackRecord.getEnterTransition(BackStackRecord.java:1056)
            at android.support.v4.app.BackStackRecord.configureTransitions(BackStackRecord.java:1138)
            at android.support.v4.app.BackStackRecord.beginTransition(BackStackRecord.java:1038)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:660)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by andkulikov** [comment]
Thanks for feedback!
Unfortunately support fragment transitions work only with common android transitions and only with Lollipop. My transitions are cannot be compatible with support lib. 
Now I don't have a plan for porting similar api, but maybe someday i will try it

**Comment by moondroid** [comment]
very bad! fragment transitions are the most useful...

**Comment by dericdesta** [comment]
A backport of fragment transitions would be awesome!

**Comment by seyedmmousavi** [comment]
Is it not possible yet?

**Comment by andkulikov** [comment]
No

**Comment by Crasheng** [comment]
is it possible now?

**Comment by andkulikov** [comment]
Still no. Support library was recently added it, but for my transitions to also work with it I need to extend support library Transition class which I don't want to do and as this approach will use not mine TransitionManager but from support library I will not be able to apply all my fixes into this usage.
If you really need it please try to use support transitions and be aware about bugs I reported for it https://medium.com/@andkulikov/support-library-for-transitions-overview-and-comparison-c41be713cf8c

**Comment by andkulikov** [comment]
Please check out the main README file. I released version 2.0.0 of Transitions-Everywhere based on AndroidX transitions. So now it will work with fragments.
