### ISSUE TITLE
[BUG] android 4.1.2

### ISSUE THREAD

**Issue by c0nnector** [andkulikov/Transitions-Everywhere#19]
This bug occurs in android 4.1.2 only(haven't checked for lower versions). Works fine with 4.3 and above. I provide as root view  **(ViewGroup) getActivity().getWindow().getDecorView().getRootView()**
. Seems that the casting is the reason of crashing
      
   ```
 java.lang.ClassCastException: android.view.ViewRootImpl cannot be cast to android.view.View            at android.transitions.everywhere.utils.ViewOverlayPreJellybean.getOverlay(ViewOverlayPreJellybean.java:123)    at android.transitions.everywhere.utils.ViewGroupOverlayUtils$BaseViewGroupOverlayUtilsImpl.initializeOverlay(ViewGroupOverlayUtils.java:53)       at android.transitions.everywhere.utils.ViewGroupOverlayUtils.initializeOverlay(ViewGroupOverlayUtils.java:156)            at android.transitions.everywhere.TransitionManager.sceneChangeRunTransition(TransitionManager.java:223)            at 
android.transitions.everywhere.TransitionManager.beginDelayedTransition(TransitionManager.java:379)
            at    android.transitions.everywhere.TransitionManager.beginDelayedTransition(TransitionManager.java:340)
            at com.example.project.views.TutorialTip.animateChanges(TutorialTip.java:97)
            at com.example.project.views.TutorialTip.showOverlay(TutorialTip.java:81)
            at com.example.project.views.TutorialTip.show(TutorialTip.java:130)
            at com.example.project.tooltips.ProfileTooltipsHelper.showTooltip(ProfileTooltipsHelper.java:151)
            at com.example.project.tooltips.ProfileTooltipsHelper.showNext(ProfileTooltipsHelper.java:130)
            at com.example.project.screens.profile.FragmentProfileMe.showTips(FragmentProfileMe.java:97)
            at     com.example.project.screens.profile.FragmentProfileMe_.access$501(FragmentProfileMe_.java:26)
            at com.example.project.screens.profile.FragmentProfileMe_$2.run(FragmentProfileMe_.java:140)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by andkulikov** [comment]
will fix it in next version. 
but for what reasons its necessary to use getRootView() instead of real container of animated views?

**Comment by c0nnector** [comment]
I wanted to cover the whole view, event the toolbar. It's easier to get the rootview rather than creating myself a container.

I did a 'temp hack' to detect the android version and set another container till a fix is available.

Thanks

**Comment by andkulikov** [comment]
ok, you can add this check for now 
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN_MR2) ..

**Comment by andkulikov** [comment]
fixed in 1.4.0

**Comment by eGorets** [comment]
Hi, I work on cyanogenmod 11, lib version is 1.4.0 and i got an exception  

06-08 13:13:36.414  19726-19726/com.spins.discoveri.dev E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=1
            at android.transitions.everywhere.utils.ArrayMap.valueAt(ArrayMap.java:389)
            at android.transitions.everywhere.Transition.pause(Transition.java:1677)



        final ViewGroup sceneRoot = (ViewGroup) this.stateMain.getParent();
        AutoTransition layoutTransition1 = new AutoTransition();

        TransitionManager.beginDelayedTransition(sceneRoot, layoutTransition1);

I use workaround

 if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN_MR2)

**Comment by andkulikov** [comment]
hm, strange case. i will try to find reasons of crash
