### ISSUE TITLE
Crashes on 4.4.4 and 4.4.2

### ISSUE THREAD

**Issue by vit001** [andkulikov/Transitions-Everywhere#52]
I am seeing crash reports from a LGE Nexus 5 (4.4.4), HTC One_M8 (4.4.4), Motorola XT1092 (4.4.4), and LGE LG-D855 (4.4.2) with the following trace:
```java.lang.NoSuchMethodError: android.util.FloatProperty.<init>
at com.transitionseverywhere.utils.FloatProperty.<init>(FloatProperty.java:15)
at com.transitionseverywhere.utils.ViewUtilsKitKat$1.<init>(ViewUtilsKitKat.java:17)
at com.transitionseverywhere.utils.ViewUtilsKitKat.<clinit>(ViewUtilsKitKat.java:17)
at com.transitionseverywhere.utils.ViewUtils.<clinit>(ViewUtils.java:177)
at com.transitionseverywhere.TransitionManager.beginDelayedTransition(TransitionManager.java:439)
```
Is this a known issue?

**Comment by andkulikov** [comment]
Hi,
Could you show full stacktrace please?

**Comment by vit001** [comment]
Sorry, not sure why the full trace didn't get pasted earlier ...
```	
java.lang.NoSuchMethodError: android.util.FloatProperty.<init>
at com.transitionseverywhere.utils.FloatProperty.<init>(FloatProperty.java:15)
at com.transitionseverywhere.utils.ViewUtilsKitKat$1.<init>(ViewUtilsKitKat.java:17)
at com.transitionseverywhere.utils.ViewUtilsKitKat.<clinit>(ViewUtilsKitKat.java:17)
at com.transitionseverywhere.utils.ViewUtils.<clinit>(ViewUtils.java:177)
at com.transitionseverywhere.TransitionManager.beginDelayedTransition(TransitionManager.java:439)
at 
```

**Comment by andkulikov** [comment]
Which transition do you provide into beginDelayedTransition? Some custom transition? Do you use FloatProperty inside? 
I am using FloatProperty in some of my projects and don't have such crash reports.

**Comment by andkulikov** [comment]
Do you still receiving crush reports? 
How do you use FloatProperty in your app?
